name: CI

on:
  push:
    branches: [master]
  pull_request:

jobs:
  code:
    name: Code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Test your example code here
