name: Slides

on:
  push:
    branches:
      - master

jobs:
  slide:
    name: Publish
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Nix
        uses: cachix/install-nix-action@v14
        with:
          install_url: https://github.com/numtide/nix-flakes-installer/releases/download/nix-2.4pre20210604_8e6ee1b/install
          extra_nix_config: |
            experimental-features = nix-command flakes
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

      - name: Get GitHub pages URL
        uses: actions/github-script@v5
        id: pages_url
        with:
          result-encoding: string
          script: |
            try {
              const pages = await github.rest.repos.getPages({
                owner: context.repo.owner,
                repo: context.repo.repo,
              });

              return pages.data.html_url;
            } catch(err) {
              if (err.status == 404) {
                return `https://${context.repo.owner}.github.io/${context.repo.repo}/`;
              }

              throw err;
            }

      - name: Build
        run: nix develop -c reveal-md --static public/ --static-dirs slides/assets  --absolute-url ${{ steps.pages_url.outputs.result }} slides/index.md

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
